# Generated by Django 5.2.6 on 2025-09-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='t_yil',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
